title: My Jekyll Site
email: your-email@example.com
description: >-
  A simple site built with Jekyll and GitHub Pages.
baseurl: "/my-jekyll-site" # your repo name, important if not at root
url: "https://vikuser99.github.io" # your GitHub Pages URL

theme: minima

plugins:
  - jekyll-feed








Add _config.yml with basic site settings and theme
